// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/sprintf/sprintf.d.ts
// Type definitions for sprintff
// Project: https://github.com/maritz/node-sprintff
// Definitions by: Carlos Ballesteros Velasco <https://github.com/soywiz>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// Imported from: https://github.com/soywiz/typescript-node-definitions/sprintff.d.ts

declare module "sprintf-js" {
  export function sprintf(fmt: string, ...args: any[]): string;
  export function vsprintf(fmt: string, args: any[]): string;
}
